@startuml
-> TokenAuthenticator: setup()
 TokenAuthenticator --> Environments: getCurrent().getXsuaaConfiguration()
 TokenAuthenticator --> Environments: getCurrent().getIasConfiguration()

Environments -> TokenAuthenticator: OAuth2ServiceConfiguration

TokenAuthenticator --> HttpClientFactory: create(OAuth2ServiceConfiguration.getClientIdentity())
HttpClientFactory -> TokenAuthenticator: CloseableHttpClient

TokenAuthenticator --> JwtValidatorBuilder: getInstance(OAuth2ServiceConfiguration).withHttpClient(CloseableHttpClient).build()
JwtValidatorBuilder -> TokenAuthenticator: CombiningValidator

-> TokenAuthenticator: anyProtectedServlet()


TokenAuthenticator --> Token: create("eyJhdW...")
Token -> TokenAuthenticator: Token

TokenAuthenticator --> CombiningValidator: validate(Token)
CombiningValidator -> TokenAuthenticator: ValidationResult
@enduml


