@startuml
-> Application: setup()
Application --> Environments: getCurrent().getIasConfiguration()

Environments -> Application: OAuth2ServiceConfiguration

Application -> JwtValidatorBuilder: getInstance(OAuth2ServiceConfiguration).build()
JwtValidatorBuilder --> Application: CombinedValidator

-> Application: anyProtectedFunction()


Application -> IasToken: new("abyJhbGci1iJSUzI1NiJ9.eyJhdW...")
IasToken --> Application: Token

Application -> CombinedValidator: validate(Token)
CombinedValidator --> Application: ValidationResult
@enduml


