@startuml
-> SecurityFilter: new()
SecurityFilter -> IasTokenAuthenticator: new()
IasTokenAuthenticator --> Environments: getCurrent().getIasConfiguration()

Environments -> IasTokenAuthenticator: OAuth2ServiceConfiguration
IasTokenAuthenticator --> SecurityFilter

-> SecurityFilter: doFilter()
SecurityFilter -> IasTokenAuthenticator: validateRequest()
IasTokenAuthenticator -> JwtValidatorBuilder: getInstance(OAuth2ServiceConfiguration).build()
JwtValidatorBuilder --> IasTokenAuthenticator: CombinedValidator

IasTokenAuthenticator -> IasToken: new("abyJhbGci1iJSUzI1NiJ9.eyJhdW...")
IasToken --> IasTokenAuthenticator: Token

IasTokenAuthenticator -> CombinedValidator: validate(Token)
CombinedValidator --> IasTokenAuthenticator: ValidationResult

IasTokenAuthenticator -> SecurityFilter: TokenAuthenticationResult

SecurityFilter -> SecurityFilter: call next filter if authenticated
@enduml


